name: Deploy Development Build

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        name: ðŸš€ Build
        runs-on: ubuntu-latest

        steps:
            - uses: pnpm/action-setup@v2
              with:
                  version: 8

            - name: ðŸ“š Checkout
              uses: actions/checkout@v3
              with:
                  token: ${{secrets.TOKEN_GH}}

            - name: ðŸŸ¢ Node
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org

            - name: ðŸ³ Prepare
              run: pnpm install

            - name: ðŸ“¦ Build package
              run: |
                  cd packages/commandkit
                  pnpm run lint && pnpm run build

            - name: âš¡ï¸ Create/update dev branch
              run: |
                  git config user.name "GitHub Actions Bot"
                  git config user.email ${{secrets.USER_EMAIL}}
                  git checkout -B dev-build
                  pnpm run build:package
                  mkdir temp_dir && mkdir temp_dir/dist/
                  cp -r packages/commandkit/dist/* temp_dir/dist
                  cp packages/commandkit/package.json temp_dir/
                  git rm -rf . && echo "node_modules/" > .gitignore
                  rm -rf apps/ && rm -rf packages
                  cp -r temp_dir/* . && rm -rf temp_dir
                  git add .
                  git commit -m "Deploy latest development build"
                  git push origin dev-build
